### ISSUE TITLE
Percentage at 0 Until Move

### ISSUE THREAD

**Issue by dan1982code** [nvdaes/placeMarkers#15]
*Place a bookmark somewhere (not at the top)
*Go to the top of the virtual document. Press NVDA+delete. We are told we are at 0%.
*Jump to the bookmark.
*Check the percentage again. It will stay at 0%. This is unexpected; expected is to report the percentage of the document where the bookmark is found.
*Move right or left one character. Now the percentage is reported correctly.

This is with Firefox 65 and PlaceMarkers 12.3.

Thanks!

**Comment by nvdaes** [comment]
Great! Good catch.
We have to use:

> review.handleCaretMove(info)

This will instruct NVDA to move the review cursor to caret if we have it configured so that review cursor follows it.
I will fix this later.

**Comment by nvdaes** [comment]
This is fixed in version 12.4, which will be available in about 35 minutes. Please download it from the website or using addonUpdater, by @josephsl
