### ISSUE TITLE
Unable to go to next bookmark

### ISSUE THREAD

**Issue by Neurrone** [nvdaes/placeMarkers#23]
## Describe the bug ##

Moving to the next bookmark fails with an error sound.

## To Reproduce ##

1. Add a bookmark anywhere in the document
2. Try to move to it with nvda+k

## Expected behavior ##
Moving to the next bookmark succeeds

## logs ##

The following log is printed:

```
ERROR - scriptHandler.executeScript (10:10:21.863) - MainThread (11088):
error executing script: <bound method GlobalPlugin.script_selectNextBookmark of <globalPlugins.placeMarkers.GlobalPlugin object at 0x041C3418>> with gesture 'NVDA+k'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "C:\Users\Dickson\AppData\Roaming\nvda\addons\placeMarkers\globalPlugins\placeMarkers\__init__.py", line 917, in script_selectNextBookmark
    moveToBookmark(nextPos)
  File "C:\Users\Dickson\AppData\Roaming\nvda\addons\placeMarkers\globalPlugins\placeMarkers\__init__.py", line 133, in moveToBookmark
    speech.speakTextInfo(info,reason=controlTypes.REASON_CARET)
AttributeError: module 'controlTypes' has no attribute 'REASON_CARET'
```

## System configuration ##
- Product version: PlaceMarkers 15.2, NVDA alpha-22222,2e37433e

## Additional context ##
Probably caused by some backwards incompatible refactoring in NVDA for 2021.1

**Comment by nvdaes** [comment]
Thanks for reporting, I"ll take care of this issue.

**Comment by nvdaes** [comment]
@Neurrone, you can test this add-on, released just for testing:

https://github.com/nvdaes/placeMarkers/releases/download/pr-24/placeMarkers-9dad8d852f1ee01715b88578ca9cac67440f27dd.nvda-addon

I'm testing it with latest alpha and seems to work.
Thanks

**Comment by nvdaes** [comment]
This is fixed for me. Also, due to changes to improve automatic checks, the add-on link provided for testing has been replaced by another one. So, I'l merge the pull request and this issue will be closed as fixed.
Thanks so much for reporting.
