### ISSUE TITLE
alt+NVDA+k, Delete Option

### ISSUE THREAD

**Issue by dan1982code** [nvdaes/placeMarkers#3]
just another feature to consider: perhaps alt+NVDA+k could have a "delete" button to delete the currently-selected bookmark. This would make it easy to clear out a bunch of bookmarks instead of moving to them using NVDA+k and deleting each one. Thank you again.

**Comment by nvdaes** [comment]
Thanks for your interest. I'll try to implement this.

**Comment by nvdaes** [comment]
@dan1982code, please, test this try release and provide feedback:

https://github.com/nvdaes/placeMarkers/releases/download/9.0-dev-i3/placeMarkers-9.0-dev-i3.nvda-addon
