### ISSUE TITLE
[Feature]: Once you land on a document, get alerted if the current document has a placemarker either in the form of a specific search or a book mark.

### ISSUE THREAD

**Issue by DGartmann** [nvdaes/placeMarkers#32]
### Problem

I am not being made aware that one or more placemarkers are available for the current document. Therefore, I tend to forget that I once made placemarkers and will start making them again and thus spending more time than necessary before I can do the things I need to do in that particular document or web page..

### Suggestion

Some sort of alert is made e.g. a sound, a message, a Braille message on my Braille display, or all of these things configurable by the user. The alert / sound / message is triggered when the document / web page I just landed on has a placemarker either in the form of a book mark or a specific search. I then don't need to go into the menues to check if there are any placemarkers for that particular page. This will improve efficiency when working with documents / web pages that I come back to after some time.

**Comment by nvdaes** [comment]
Hello, I've been thinking about this problem and investigating several events, like gainFocus, focusEntered and foreground, but these may miss or produce repeated alerts, so they aren't reliable.
I think that these kind of automatic alerts are difficult to implement in a global plugin like this. Imo, this maybe better achieved if this can be done in NVDA's core, but seems it won't happens. See

https://github.com/nvaccess/nvda/issues/88

Anyway, I'll ask in the NVDA developer list explaining technical details. In case I don't get an answer, I'll ask you if you think that this can be presented with the command to see the name of the file for place markers (see the add-on documentation).
Also, you can press NVDA+alt+k on NVDA+shift+control+f to check if bookmarks or specific search texts are available for the current document.

**Comment by DGartmann** [comment]
I think that the solution you propose is worth trying out. Thanks for looking into this.

**Comment by nvdaes** [comment]
Hello, after our private conversation, I'll implement this via the command to see the filename of placeMarkers.
