### ISSUE TITLE
[Bug]: in browsers based on project Chromeum this addon includes whole title bar to title a files with data about placemarkers on particular pages (also number of opened tabs)

### ISSUE THREAD

**Issue by gregjozk** [nvdaes/placeMarkers#38]
### Summary

Added placemarkers are visible only when same number of tabs are opened as on a moment of its creation. If you close/open one or more tabs, placemarkers are not visible anymore.

### To reproduce

- in chromeum based web browser such as Chrome, Edge etc open webpage, where you want to add placemarker
- add placemarker
- open a new tab
- on page, where a placemarker has been created, try to go to it.

### Expected behavior

NVDA should see and jump to previous/next placemarker instead of reporting, that there is no placemarkers.

### Version

19.0.1

### Additional context

I don't know, but as I saw in the placemarkers folder, files with data about particular page are named as title bar in browsers. unfortunately, chromeum browsers there include also a number of currently opened tabs.
So, there are files with name e.g. of "webpage + x more pages – Personal profile – Microsoft​ Edge.pickle".

**Comment by nvdaes** [comment]
Hello:

Maybe I'm missing something. I followed the following stepsinGoogle Chrome 100:

1. Open Google.com, where I have added a place marker.
2. Open NV Access website, where I have another place marker.
3. Try tomove the cursor to both bookmarks in both websites.
This works for me. Can you provide more info please? Thanks

**Comment by gregjozk** [comment]
Hello,

last test was done inMicrosoft Edge version 99.0.1150.55, but saw it also in Chrome some days ago.
Which information will help you to investigate a problem?

**Comment by nvdaes** [comment]
Hello, please provide the title of the pages presented when you press NVDA+t. We may need to use other values instead or in addition to title.

**Comment by gregjozk** [comment]
Hello:

----- begin -----

IO - speech.speech.speak (00:10:36.745) - MainThread (15328):
Speaking ['Začetni položaj odseka dnevnika se je naznačil, ponovni
pritisk ga bo preslikal v odložišče']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:42.316) - winInputHook (10344):
Input: kb(desktop):NVDA+t
IO - speech.speech.speak (00:10:42.344) - MainThread (15328):
Speaking ['Computer Programming for Absolu in še 3 strani – Osebni
profil – Microsoft\u200b Edge']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:44.690) - winInputHook (10344):
Input: kb(desktop):control+tab
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:49.139) - winInputHook (10344):
Input: kb(desktop):NVDA+t
IO - speech.speech.speak (00:10:49.160) - MainThread (15328):
Speaking ['Nov zavihek in še 3 strani – Osebni profil – Microsoft\u200b Edge']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:52.184) - winInputHook (10344):
Input: kb(desktop):control+tab
IO - speech.speech.speak (00:10:52.368) - MainThread (15328):
Speaking ['BabyCam', 'dokument', CancellableSpeech (still valid)]
IO - speech.speech.speak (00:10:52.373) - MainThread (15328):
Speaking ['gumb', 'Poslušaj 🔊']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:53.792) - winInputHook (10344):
Input: kb(desktop):NVDA+t
IO - speech.speech.speak (00:10:53.821) - MainThread (15328):
Speaking ['BabyCam in še 3 strani – Osebni profil – Microsoft\u200b Edge']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:56.937) - winInputHook (10344):
Input: kb(desktop):control+tab
IO - speech.speech.speak (00:10:57.199) - MainThread (15328):
Speaking ['Domovina | Glasniki zamolčanega Domovina.je', 'dokument',
CancellableSpeech (still valid)]
IO - speech.speech.speak (00:10:57.207) - MainThread (15328):
Speaking ['naslov', 'nivo 2', 'obiskana', 'povezava', 'Mediana za RTV
na vrh postavlja Goloba, povprečje anket še vedno Janšo']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:10:59.730) - winInputHook (10344):
Input: kb(desktop):NVDA+t
IO - speech.speech.speak (00:10:59.742) - MainThread (15328):
Speaking ['Domovina | Glasniki zamolčanega Domovina.je in še 3 strani
– Osebni profil – Microsoft\u200b Edge']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:11:06.639) - winInputHook (10344):
Input: kb(desktop):control+tab
IO - speech.speech.speak (00:11:06.737) - MainThread (15328):
Speaking ['Computer Programming for Absolu', 'dokument',
CancellableSpeech (still valid)]
IO - speech.speech.speak (00:11:06.743) - MainThread (15328):
Speaking ['grafika', 'Packt>\n']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:11:08.806) - winInputHook (10344):
Input: kb(desktop):NVDA+t
IO - speech.speech.speak (00:11:08.821) - MainThread (15328):
Speaking ['Computer Programming for Absolu in še 3 strani – Osebni
profil – Microsoft\u200b Edge']
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture
(00:11:15.677) - winInputHook (10344):
Input: kb(desktop):control+shift+NVDA+f1

----- end -----

best regards,
Jožef

2022-04-04 21:44 GMT+02.00, Noelia Ruiz Martínez ***@***.***>:

**Comment by nvdaes** [comment]
Hi again. Please provide the URLs to see if I can reproduce this. Titles seem to be distinguished properly, so the add-on should work as expected. Thanks

**Comment by gregjozk** [comment]
Hello,

unfortunately two of them are local (one is file and one is in local
network), so, I can provide only url for Domovina:
www.domovina.je

now I've made some tests and problem is only on local file. probably,
because the html document is named "index.html"? in placemarkers
folder it is titled as "Computer Programming for Absolu in še 4 strani
– Osebni profil – Microsoft​ Edge - index.html"

Because it is a copyrighted file, I can send it only on personal mail
with hope, that it will be destroyed after investigation.

thanks a lot.

best regards,
Jožef

2022-04-05 7:09 GMT+02.00, Noelia Ruiz Martínez ***@***.***>:

**Comment by nvdaes** [comment]
Hello:

If you send me the file privately, it will be destroyed after
investigation. Be aware: I cannot ensure that investigation will be
successful.
Cheers

2022-04-05 7:59 GMT+02:00, gregjozk ***@***.***>:
