### ISSUE TITLE
Update to documentation for clarity

### ISSUE THREAD

**Issue by britechguy** [nvdaes/placeMarkers#44]
### Problem

The terms placemarker and bookmarks seem to be used interchangeably

### Suggestion

Since the term bookmarks is widely used in all Chromium-based browsers except MS-Edge, as well as Firefox, the documentation is somewhat confusing.

After reading it twice, it appears that placemarkers are what is meant throughout, but that term is not used consistently to refer to them.  The documentation would be vastly more clear if the term placemarker alone were used.

**Comment by britechguy** [comment]
You're quite welcome.  I see how much work you put into not only your own add-ons, but just NVDA add-ons in general.  I also see how much you value clarity, so I knew you'd take this in the spirit it was intended.

**Comment by nvdaes** [comment]
Fixed via #45
